<?xml version="1.0" encoding="UTF-8"?>
<testrun name="HelloTest" project="J3Labs" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="com.jlcindia.Junit3.HelloTest" time="0.0">
    <testcase name="testGetMassage1" classname="com.jlcindia.Junit3.HelloTest" time="0.0"/>
    <testcase name="testGetMassage2" classname="com.jlcindia.Junit3.HelloTest" time="0.0">
      <failure>junit.framework.AssertionFailedError&#13;
	at junit.framework.Assert.fail(Assert.java:47)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:20)&#13;
	at junit.framework.Assert.assertNotNull(Assert.java:217)&#13;
	at junit.framework.Assert.assertNotNull(Assert.java:210)&#13;
	at com.jlcindia.Junit3.HelloTest.testGetMassage2(HelloTest.java:28)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:164)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:130)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&#13;
	at junit.framework.TestResult.run(TestResult.java:109)&#13;
	at junit.framework.TestCase.run(TestCase.java:120)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:225)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
